[package]
name = "simple-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
auth = { path = "./auth"}
clap = { version = "4.5.18", features = ["derive"] }

[workspace]
members = [
    "auth",
]
